apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: climate-watch
  labels:
    name: indonesia-platform-staging
  name: indonesia-platform-staging
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: indonesia-platform-staging
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - webapps
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - indonesia-platform-staging
              topologyKey: kubernetes.io/hostname
      containers:
      - name: indonesia-platform-staging
        image: vizzuality/indonesia-platform
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: CW_FILES_PREFIX
            value: 'climatewatch.org/staging.climatewatch.org/indonesia/'
          - name: RACK_ENV
            value: production
          - name: RAILS_ENV
            value: production
          - name: PORT
            value: "3000"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: HTTP_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: CW_AUTH_USERNAME
          - name: HTTP_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: appsecrets
                key: CW_AUTH_PASSWORD
          - name: POSTGRES_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CW_INDONESIA_POSTGRES_URL_STAGING
          - name: SHARED_POSTGRES_URL
            valueFrom:
              secretKeyRef:
                  name: dbsecrets
                  key: CW_SHARED_POSTGRES_URL_STAGING
          - name: S3_BUCKET_NAME
            value: "wri-sites"
          - name: AWS_REGION
            value: "eu-west-1"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: CW_PLATFORMS_S3_ACCESS_KEY
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: CW_PLATFORMS_S3_SECRET_ACCESS_KEY
          - name: REDIS_SERVER
            value: redis://localhost:6379

        ports:
          - containerPort: 3000

      - name: indonesia-platform-sidekiq
        image: vizzuality/indonesia-platform
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - sidekiq
        env:
          - name: CW_FILES_PREFIX
            value: 'climatewatch.org/staging.climatewatch.org/indonesia/'
          - name: AWS_REGION
            value: eu-west-1
          - name: RACK_ENV
            value: production
          - name: RAILS_ENV
            value: production
          - name: PORT
            value: "3000"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: S3_BUCKET_NAME
            value: "wri-sites"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: CW_PLATFORMS_S3_ACCESS_KEY
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: CW_PLATFORMS_S3_SECRET_ACCESS_KEY
          - name: POSTGRES_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CW_INDONESIA_POSTGRES_URL_STAGING
          - name: REDIS_SERVER
            value: redis://localhost:6379
      - name: redis
        image: redis
        ports:
         - containerPort: 6379
        resources:
         requests:
           memory: "0Mi"
           cpu: "0m"

      restartPolicy: Always
